### ISSUE TITLE
Action fails on startup

### ISSUE THREAD

**Issue by Plabick** [kpurdon/openapi-generator-action#1]
A version of this action fails at startup when run on GitHub's Ubuntu-Latest build agent. 

### Usage: 
```yaml
      - name: OpenAPI Generator Action
        uses: kpurdon/openapi-generator-action@v0.0.1
        with:
            args: generate -i API-Design.yaml -g html -o /docs
```

### Result: 
`[error]'openapitools/openapi-generator-cli' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.`
<img width="936" alt="Screen Shot 2021-12-20 at 7 43 04 AM" src="https://user-images.githubusercontent.com/7085883/146768930-0c0d7224-b303-49a0-921b-5c1d80384f28.png">
