### ISSUE TITLE
Unable to run generator action locally using https://github.com/nektos/act

### ISSUE THREAD

**Issue by amikofalvy** [kpurdon/openapi-generator-action#3]
I'm trying to configure a pipeline using your github container action. I've been running github actions locally using https://github.com/nektos/act.

I've created the following workflow file to define the github actions jobs that will generate sdk using the openapi-generator:
```
name: OpenApiGenerator
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  MakeSdk:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SDK job
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/yaml/petstore.yaml -g typescript-fetch -o ./generated-code"
```

This is the output from the local action run:
```
$ act -j MakeSdk
[OpenApiGenerator/MakeSdk] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
[OpenApiGenerator/MakeSdk]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=false
[OpenApiGenerator/MakeSdk]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[OpenApiGenerator/MakeSdk]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[OpenApiGenerator/MakeSdk]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[OpenApiGenerator/MakeSdk] ⭐  Run Generate SDK job
INFO[0001]   ☁  git clone 'https://github.com/kpurdon/openapi-generator-action' # ref=v0.0.3 
[OpenApiGenerator/MakeSdk]   🐳  docker pull image=openapitools/openapi-generator-cli platform= username= forcePull=false
[OpenApiGenerator/MakeSdk]   🐳  docker create image=openapitools/openapi-generator-cli platform= entrypoint=[] cmd=["generate" "-i" "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/yaml/petstore.yaml" "-g" "typescript-fetch" "-o" "./generated-code"]
[OpenApiGenerator/MakeSdk]   🐳  docker run image=openapitools/openapi-generator-cli platform= entrypoint=[] cmd=["generate" "-i" "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/yaml/petstore.yaml" "-g" "typescript-fetch" "-o" "./generated-code"]
| /usr/local/bin/docker-entrypoint.sh: line 27: java: command not found
| /usr/local/bin/docker-entrypoint.sh: line 38: exec: java: not found
[OpenApiGenerator/MakeSdk]   ❌  Failure - Generate SDK job
Error: exit with `FAILURE`: 127
```

You can see that the docker-entrypoint.sh script is being executed, but it looks like java command is not found.

I haven't tested this action with github's true action runner yet. Perhaps this is just an issue with compatibility with nekos/act.

In any case, maybe you can provide guidance on how you have been testing out your own actions locally?
